require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/copies", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Copy. As you add validations to Copy, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # CopiesController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      Copy.create! valid_attributes
      get copies_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      copy = Copy.create! valid_attributes
      get copy_url(copy), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Copy" do
        expect {
          post copies_url,
               params: { copy: valid_attributes }, headers: valid_headers, as: :json
        }.to change(Copy, :count).by(1)
      end

      it "renders a JSON response with the new copy" do
        post copies_url,
             params: { copy: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Copy" do
        expect {
          post copies_url,
               params: { copy: invalid_attributes }, as: :json
        }.to change(Copy, :count).by(0)
      end

      it "renders a JSON response with errors for the new copy" do
        post copies_url,
             params: { copy: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested copy" do
        copy = Copy.create! valid_attributes
        patch copy_url(copy),
              params: { copy: invalid_attributes }, headers: valid_headers, as: :json
        copy.reload
        skip("Add assertions for updated state")
      end

      it "renders a JSON response with the copy" do
        copy = Copy.create! valid_attributes
        patch copy_url(copy),
              params: { copy: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to eq("application/json")
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the copy" do
        copy = Copy.create! valid_attributes
        patch copy_url(copy),
              params: { copy: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested copy" do
      copy = Copy.create! valid_attributes
      expect {
        delete copy_url(copy), headers: valid_headers, as: :json
      }.to change(Copy, :count).by(-1)
    end
  end
end
