test:
  adapter: mysql2
  username: root
  password: mypw
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: mydb_dev

test:
  adapter: mysql2
  username: root
  password: mypw
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: mydb_test

production:
  adapter: mysql2
  username: root
  password: mypw
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: mydb
